import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";

import {
  discoverProxy,
  isReachable,
  normalizeProxyUrl,
  parseMixedPort,
  parseNestedFlag,
  parseTopLevelFlag,
  parseWindowsProxyServer,
  probeTcp,
  readClashMixedPort,
  readClashTunEnabled,
  readEnvProxy,
  stripQuotes,
} from "../lib/detect.js";

/** A path that never exists, so clash detection stays hermetic in tests. */
const NO_CLASH_FILES = { files: [path.join(os.tmpdir(), "dsh-wfp-absent-config.yaml")] };

test("normalizeProxyUrl accepts http(s) and the host:port shorthand", () => {
  assert.equal(normalizeProxyUrl("127.0.0.1:7897"), "http://127.0.0.1:7897");
  assert.equal(normalizeProxyUrl("http://127.0.0.1:7897"), "http://127.0.0.1:7897");
  assert.equal(normalizeProxyUrl("https://proxy.example:8443"), "https://proxy.example:8443");
  assert.equal(normalizeProxyUrl("  http://127.0.0.1:7890  "), "http://127.0.0.1:7890");
});

test("normalizeProxyUrl rejects empty, non-string and non-http schemes", () => {
  assert.equal(normalizeProxyUrl(""), undefined);
  assert.equal(normalizeProxyUrl("   "), undefined);
  assert.equal(normalizeProxyUrl(7897), undefined);
  assert.equal(normalizeProxyUrl("socks5://127.0.0.1:1080"), undefined);
  assert.equal(normalizeProxyUrl("http://"), undefined);
});

test("stripQuotes removes one pair of surrounding quotes", () => {
  assert.equal(stripQuotes('"7897"'), "7897");
  assert.equal(stripQuotes("'7897'"), "7897");
  assert.equal(stripQuotes("7897"), "7897");
  assert.equal(stripQuotes('"'), '"');
});

test("parseMixedPort reads the mixed listener only", () => {
  assert.equal(parseMixedPort("# Generated by Clash Verge\nmixed-port: 7897\n"), 7897);
  assert.equal(parseMixedPort('mixed-port: "7897"\n'), 7897);
  assert.equal(parseMixedPort("verge_mixed_port: 7890\n"), 7890);
  assert.equal(parseMixedPort("socks-port: 7898\n"), undefined);
  assert.equal(parseMixedPort("# mixed-port: 7897\n"), undefined);
  assert.equal(parseMixedPort("mixed-port: 0\n"), undefined);
  assert.equal(parseMixedPort("mixed-port: not-a-port\n"), undefined);
  assert.equal(parseMixedPort(undefined), undefined);
});

test("readClashMixedPort returns the port and the file that supplied it", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-"));
  try {
    const file = path.join(dir, "config.yaml");
    fs.writeFileSync(file, "ipv6: true\nmixed-port: 7897\n", "utf8");
    assert.deepEqual(readClashMixedPort({ files: [file] }), { port: 7897, file });
    assert.equal(readClashMixedPort({ files: [path.join(dir, "missing.yaml")] }), undefined);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("parseWindowsProxyServer handles both WinINET notations", () => {
  assert.deepEqual(parseWindowsProxyServer("127.0.0.1:7897"), { url: "http://127.0.0.1:7897", source: "windows-registry" });
  const perScheme = parseWindowsProxyServer("http=127.0.0.1:7890;https=127.0.0.1:7897");
  assert.equal(perScheme.url, "http://127.0.0.1:7897");
  assert.equal(parseWindowsProxyServer(""), undefined);
  assert.equal(parseWindowsProxyServer("; ;"), undefined);
});

test("readEnvProxy ranks the plugin variable first", () => {
  assert.equal(readEnvProxy({ HTTPS_PROXY: "http://127.0.0.1:7897" }).source, "env:HTTPS_PROXY");
  assert.equal(readEnvProxy({ DSH_WEB_FETCH_PROXY: "http://127.0.0.1:1", HTTPS_PROXY: "http://127.0.0.1:2" }).url, "http://127.0.0.1:1");
  assert.equal(readEnvProxy({ all_proxy: "socks5://127.0.0.1:1080" }), undefined);
  assert.equal(readEnvProxy({}), undefined);
});

test("probeTcp and isReachable follow a real listener", async () => {
  const server = net.createServer();
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const port = server.address().port;
  try {
    assert.equal(await probeTcp("127.0.0.1", port, 1000), true);
    assert.equal(await isReachable("http://127.0.0.1:" + port + "/", 1000), true);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
  assert.equal(await probeTcp("127.0.0.1", port, 400), false);
  assert.equal(await isReachable("not a url", 400), false);
});

test("discoverProxy honours an explicit config value", async () => {
  const hit = await discoverProxy({ explicit: "127.0.0.1:7897", reachable: async () => true });
  assert.deepEqual(hit, { url: "http://127.0.0.1:7897", source: "config" });
  assert.equal(await discoverProxy({ explicit: "127.0.0.1:7897", reachable: async () => false }), undefined);
  assert.equal(await discoverProxy({ explicit: "socks5://127.0.0.1:1080", reachable: async () => true }), undefined);
});

test("discoverProxy falls through environment, clash config and the port probe", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-"));
  try {
    const file = path.join(dir, "config.yaml");
    fs.writeFileSync(file, "mixed-port: 7899\n", "utf8");

    const fromEnv = await discoverProxy({
      explicit: "auto",
      env: { HTTPS_PROXY: "http://127.0.0.1:7897" },
      clashOptions: NO_CLASH_FILES,
      reachable: async (url) => url === "http://127.0.0.1:7897",
    });
    assert.equal(fromEnv.source, "env:HTTPS_PROXY");

    const fromClash = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: { files: [file] },
      reachable: async (url) => url === "http://127.0.0.1:7899",
    });
    assert.equal(fromClash.url, "http://127.0.0.1:7899");
    assert.ok(fromClash.source.startsWith("clash-config:"));

    const fromProbe = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: NO_CLASH_FILES,
      ports: [1234, 7897],
      reachable: async (url) => url === "http://127.0.0.1:7897",
    });
    assert.deepEqual(fromProbe, { url: "http://127.0.0.1:7897", source: "port-probe:7897" });

    const nothing = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: NO_CLASH_FILES,
      ports: [1234],
      reachable: async () => false,
    });
    assert.equal(nothing, undefined);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("parseTopLevelFlag reads only unindented switches", () => {
  assert.equal(parseTopLevelFlag("enable_tun_mode: true\n", "enable_tun_mode"), true);
  assert.equal(parseTopLevelFlag("enable_tun_mode: false\n", "enable_tun_mode"), false);
  assert.equal(parseTopLevelFlag("tun:\n  enable_tun_mode: true\n", "enable_tun_mode"), undefined);
  assert.equal(parseTopLevelFlag("# enable_tun_mode: true\n", "enable_tun_mode"), undefined);
  assert.equal(parseTopLevelFlag(undefined, "enable_tun_mode"), undefined);
});

test("parseNestedFlag reads a block scalar and stops at the block edge", () => {
  const text = "mixed-port: 7897\ntun:\n  enable: true\n  stack: gvisor\nsecret: x\n";
  assert.equal(parseNestedFlag(text, "tun", "enable"), true);
  assert.equal(parseNestedFlag("tun:\n  enable: false\n", "tun", "enable"), false);
  // an `enable` that appears after the block ended must not be picked up
  assert.equal(parseNestedFlag("tun:\n  stack: gvisor\nenable: true\n", "tun", "enable"), undefined);
  assert.equal(parseNestedFlag("dns:\n  enable: true\n", "tun", "enable"), undefined);
});

test("readClashTunEnabled prefers the UI switch, then the runtime block", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-tun-"));
  try {
    const verge = path.join(dir, "verge.yaml");
    const runtime = path.join(dir, "config.yaml");
    const missing = path.join(dir, "nope.yaml");

    fs.writeFileSync(verge, "tun_tray_icon: false\nenable_tun_mode: true\n", "utf8");
    assert.equal(readClashTunEnabled({ files: [verge] }), true);

    fs.writeFileSync(verge, "enable_tun_mode: false\n", "utf8");
    assert.equal(readClashTunEnabled({ files: [verge] }), false);

    fs.writeFileSync(runtime, "tun:\n  enable: true\n  stack: gvisor\n", "utf8");
    assert.equal(readClashTunEnabled({ files: [runtime] }), true);

    assert.equal(readClashTunEnabled({ files: [missing] }), undefined);
    assert.equal(readClashTunEnabled({ files: [missing, runtime] }), true);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("the UI switch beats a stale generated runtime block", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-stale-"));
  try {
    const verge = path.join(dir, "verge.yaml");
    const runtime = path.join(dir, "config.yaml");
    // The real Clash Verge shape: verge.yaml flips immediately, config.yaml lags behind.
    fs.writeFileSync(verge, "enable_tun_mode: true\nenable_system_proxy: false\n", "utf8");
    fs.writeFileSync(runtime, "tun:\n  enable: false\n  stack: gvisor\n", "utf8");
    assert.equal(readClashTunEnabled({ files: [verge, runtime] }), true);

    // And the reverse direction: switching off must not be overridden by a stale block.
    fs.writeFileSync(verge, "enable_tun_mode: false\n", "utf8");
    fs.writeFileSync(runtime, "tun:\n  enable: true\n", "utf8");
    assert.equal(readClashTunEnabled({ files: [verge, runtime] }), false);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

/** Discover options with both switch readers pinned, so the gate never reads the host. */function gateOptions(extra) {
  return Object.assign({
    explicit: "auto",
    env: {},
    clashOptions: NO_CLASH_FILES,
    readSystemProxy: () => undefined,
    ports: [7897],
    reachable: async (url) => url === "http://127.0.0.1:7897",
  }, extra);
}

test("the toggles trigger keeps web_fetch direct while both switches are off", async () => {
  const hit = await discoverProxy(gateOptions({ trigger: "toggles" }));
  assert.equal(hit.gated, true);
  assert.match(hit.reason, /直连/);
});

test("the toggles trigger opens for the Windows system proxy", async () => {
  const hit = await discoverProxy(gateOptions({
    trigger: "toggles",
    readSystemProxy: () => ({ url: "http://127.0.0.1:7897", source: "windows-registry" }),
  }));
  assert.equal(hit.url, "http://127.0.0.1:7897");
  assert.equal(hit.gated, undefined);
});

test("the toggles trigger opens for Clash TUN mode", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-gate-"));
  try {
    const runtime = path.join(dir, "config.yaml");
    fs.writeFileSync(runtime, "mixed-port: 7897\ntun:\n  enable: true\n", "utf8");
    const hit = await discoverProxy(gateOptions({ trigger: "toggles", clashOptions: { files: [runtime] } }));
    assert.equal(hit.url, "http://127.0.0.1:7897");
    assert.ok(hit.source.startsWith("clash-config:"));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("explicit intent ignores the gate", async () => {
  const fromEnv = await discoverProxy(gateOptions({
    trigger: "toggles",
    env: { HTTPS_PROXY: "http://127.0.0.1:7897" },
  }));
  assert.equal(fromEnv.source, "env:HTTPS_PROXY");

  const explicit = await discoverProxy(gateOptions({ trigger: "toggles", explicit: "127.0.0.1:7897" }));
  assert.equal(explicit.source, "config");
});

test("trigger reachable keeps the legacy always-discover behaviour", async () => {
  const hit = await discoverProxy(gateOptions({ trigger: "reachable" }));
  assert.deepEqual(hit, { url: "http://127.0.0.1:7897", source: "port-probe:7897" });
});
